name: progmob_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  font_awesome_flutter: ">= 4.7.0"
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_svg: ^0.22.0

flutter:
  uses-material-design: true
  assets:
    - assets/welcome.png
    - assets/Login.png
    - assets/google.png
    - assets/twitter.png
    - assets/Forgotpassword.png
    - assets/welcome1.png
    - assets/welcome2.png
    - assets/welcome3.png
    - assets/avatar.jpg
    - assets/icons/gofood.svg
    - assets/icons/goride.svg
    - assets/icons/gosend.svg
    - assets/icons/gocar.svg
    - assets/icons/goclub.svg
    - assets/icons/gomart.svg
    - assets/icons/gopulsa.svg
    - assets/icons/other.svg
